ANALYZE sdmin.adm_dw_wrk_rst (dw_wrknm);
ANALYZE sdmin.cls_cr_rnd_prm_mmcls (plyno);
ANALYZE sdmin.cls_ltrm_cvr_rnd_prm (plyno);
ANALYZE sdmin.cls_ltrm_mnrt (plyno);
ANALYZE sdmin.cus_ctm (ctmno);
ANALYZE sdmin.igd_gd (gdcd);
ANALYZE sdmin.igd_gd_csf (gd_csfcd);
ANALYZE sdmin.igd_gd_cvr_acm_rk (acm_rkcd, gdcd, cvrcd);
ANALYZE sdmin.ins_cmins_ins_re_cls (rn_rtro_cr_flgcd, cls_bjno, re_dlno, pstcd, rincd);
ANALYZE sdmin.ins_cr_cvr (plyno);
ANALYZE sdmin.ins_cr_dh_stf_crr (plyno);
ANALYZE sdmin.ins_cr_relpc (plyno);
ANALYZE sdmin.ins_incm_prm (plyno);
ANALYZE sdmin.ins_ins_cr (plyno);
ANALYZE sdmin.ins_prm_pym_pr (plyno);
ANALYZE sdmin.m_ccr_cr_ins_cr (plyno);
ANALYZE sdmin.m_cod_bzus_ins_itm_csfcd (ins_imcd);
ANALYZE sdmin.m_cod_cvrcd (cvrcd);
ANALYZE sdmin.m_cod_gdcd (gdcd);
ANALYZE sdmin.m_lcr_ltins_cr (plyno);
ANALYZE sdmin.m_lcr_ltrm_incm_prm (plyno);
ANALYZE sdmin.m_lwt_dm_rd_rptg_list (rcp_nv_seqno, ins_imcd, dm_rd_rptg_seqno, cvgcd, adm_chrps_stfno);
ANALYZE sdmin.m_org_bz_orgn (stfno);
ANALYZE sdmin.m_org_mthy_bz_orgn (stfno);
ANALYZE sdmin.m_org_org_ordr (orgcd);
ANALYZE sdmin.m_sam_bz_fml_styrt (stfno);
ANALYZE sdmin.m_sam_dyb_bzfml_prsn_crst (stfno);
ANALYZE sdmin.m_sam_stf_srtr_orgn (stfno);
ANALYZE sdmin.m_sam_vl_wkdgr_adm (vl_yr, vl_wkdgr);
ANALYZE sdmin.met_subo_rel_cd_defn (subo_rel_tpcd, lvl_1_dtcd, lvl_2_dtcd, lvl_3_dtcd, lvl_4_dtcd, lvl_5_dtcd, ap_nddt, ap_strdt);
ANALYZE sdmin.sam_aw_cc_achv (stfno);
ANALYZE sdmin.sam_aw_cc_achv_stf (stfno);
ANALYZE sdmin.sam_aw_py_spc (stfno);
ANALYZE sdmin.sam_incm_prm_bz_av (plyno);
ANALYZE sdmin.sam_org (orgcd);
ANALYZE sdmin.sam_stf (stfno);
ANALYZE sdmin.v_calendar (calendar_date);
